project:
  type: website
  output-dir: docs

website:
  title: "Erdem Karaköylü"
  navbar:
    left:
      - href: blog.qmd
        text: Blog
      - href: portfolio.qmd
        text: Portfolio
      - href: resume.qmd
        text: Resume
  
  body-footer: |
    <!-- 100% privacy-first analytics -->
    <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
    <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>

format:
  html:
    theme: darkly
    css: styles.css
    toc: true





